name: Generate Ban Lists

on:
  schedule:
    - cron: '0 */2 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  generate-lists:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install ClickHouse client
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates dirmngr
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4
        echo "deb https://repo.clickhouse.com/deb/stable/ main/" | sudo tee /etc/apt/sources.list.d/clickhouse.list
        sudo apt-get update
        sudo apt-get install -y clickhouse-client
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
    - name: Run SQL query and generate lists
      env:
        CH_HOST: ${{ secrets.CH_HOST }}
        CH_PORT: ${{ secrets.CH_PORT }}
        CH_DATABASE: ${{ secrets.CH_DATABASE }}
      run: |
        mkdir -p ~/AutoGeneratedList
        
        clickhouse-client --host=$CH_HOST --port=$CH_PORT --database=$CH_DATABASE --query="$(cat /tools/banned.sql)" --format CSVWithNames > ~/AutoGeneratedList/all_results.csv
        
        awk -F',' 'NR>1 {print > ("~/AutoGeneratedList/" $11 ".csv")}' ~/AutoGeneratedList/all_results.csv
        awk -F',' 'NR>1 {print $3 > ("~/AutoGeneratedList/" $11 ".txt")}' ~/AutoGeneratedList/all_results.csv
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ~/AutoGeneratedList
        git commit -m "Update ban lists" -a || echo "No changes to commit"
        git push
